// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN7KBeP0QrH2JPhO71zZ4_J4iUC_t9s0k',
    appId: '1:474379223776:web:2c16116d082cd58b0d4685',
    messagingSenderId: '474379223776',
    projectId: 'kook-ef6fa',
    authDomain: 'kook-ef6fa.firebaseapp.com',
    storageBucket: 'kook-ef6fa.appspot.com',
    measurementId: 'G-VYW4RTCQDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcl_Ve5m-b-Te5aQwrZsGDq2TRUR6fVjw',
    appId: '1:474379223776:android:20e0441dd6549d8e0d4685',
    messagingSenderId: '474379223776',
    projectId: 'kook-ef6fa',
    storageBucket: 'kook-ef6fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLfKSrZGW_uAEJ-I9bBTK55Dom0FDGaI',
    appId: '1:474379223776:ios:a17080214ebefb8c0d4685',
    messagingSenderId: '474379223776',
    projectId: 'kook-ef6fa',
    storageBucket: 'kook-ef6fa.appspot.com',
    iosBundleId: 'com.example.todomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLfKSrZGW_uAEJ-I9bBTK55Dom0FDGaI',
    appId: '1:474379223776:ios:a17080214ebefb8c0d4685',
    messagingSenderId: '474379223776',
    projectId: 'kook-ef6fa',
    storageBucket: 'kook-ef6fa.appspot.com',
    iosBundleId: 'com.example.todomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN7KBeP0QrH2JPhO71zZ4_J4iUC_t9s0k',
    appId: '1:474379223776:web:2c16116d082cd58b0d4685',
    messagingSenderId: '474379223776',
    projectId: 'kook-ef6fa',
    authDomain: 'kook-ef6fa.firebaseapp.com',
    storageBucket: 'kook-ef6fa.appspot.com',
    measurementId: 'G-VYW4RTCQDS',
  );

}